server:
  port: '8080'
  servlet:
    context-path: /api/v1
security:
  api:
    key: prodkey
spring:
  docker:
    compose:
      enabled: 'true'
      file: src/infra/docker-compose.yml
selenium:
  driver-path: "http://seleniarm:4444"